### ISSUE TITLE
Archive an instance of the software at time of MEE publication

### ISSUE THREAD

**Issue by trashbirdecology** [christophhoeppke/maxnodf#1]
Unless this has already been done and is not yet linked to in the repository, I hope you will archive the instance of your software that is associated with the MEE article (doi: 10.1111/2041-210X.13545) in a permanent location, especially given this software is published on a personal github account.

**Comment by christophhoeppke** [comment]
Dear Jessica, 

The release of maxnodf used in doi: 10.1111/2041-210X.13545 has been published on Cran <https://cran.r-project.org/web/packages/maxnodf/index.html>. Please let me know if
this will be appropriate for permanent storage. 

Kindest regards,

Christoph

**Comment by trashbirdecology** [comment]
Nice! Sorry I missed this. 

BTW, all these issues are consequence of both your article appearing on MEE homepage and my quick investigation in to the reproducibility and transparency of R packages within the journal. :)
