### ISSUE TITLE
Update algorithm reference in README and other related documentation

### ISSUE THREAD

**Issue by trashbirdecology** [christophhoeppke/maxnodf#2]
The following quote from the [MEE article](https://besjournals.onlinelibrary.wiley.com/doi/epdf/10.1111/2041-210X.13545) references an alternative version of the algorithm (Simmons et al, 2019) that does not appear in the README (haven't checked other doc).

> (ii) the algorithm proposed by Simmons, Hoeppke & Sutherland(2019); and (iii) the original algorithm proposed by Song et al. (2017). 

**If Simmons et al. (2019) algorithm is indeed used in this package**,  please update README and all documentation to reflect that. 

If the package does not use that version, please loudly close this issue.

**Comment by SimmonsBI** [comment]
The Simmons et al. (2019) algorithm only occurs in Simmons et al. (2019) and is not in this package.
